version: '3'

services:
  dbeiya:
    image: postgres
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres-dataeiya:/var/lib/postgresql/data
    networks:
      - db-neteiya
  django:
    build: ./api
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.envs/.postgres
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - dbeiya
    networks:
      - db-neteiya
  frontend:
    restart: always
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "4000:3000"
    depends_on:
      - django
    networks:
      - db-neteiya
networks:
  db-neteiya:
    driver: bridge