# Generated by Django 4.0.2 on 2022-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='Id_localidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='Id_municipio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
