# Generated by Django 4.0.2 on 2022-05-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_localidad_id_localidad_municipio_id_municipio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localidad',
            old_name='Id_localidad',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='Id_municipio',
            new_name='municipio',
        ),
    ]
