# Generated by Django 4.0.2 on 2022-05-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_paradas_id_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradas',
            name='Longitud',
        ),
        migrations.RemoveField(
            model_name='paradas',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='paradas',
            name='latitud',
        ),
    ]
