# Generated by Django 4.0.2 on 2022-05-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_ruta_vehiculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta_vehiculos',
            name='id_ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.ruta'),
        ),
        migrations.AlterField(
            model_name='ruta_vehiculos',
            name='id_vehiculos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculos'),
        ),
    ]
